# Generated by Django 4.2.1 on 2023-06-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_profilepicture'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participatedPost', models.ManyToManyField(to='posts.posts')),
                ('participatingUsers', models.ManyToManyField(to='users.users')),
            ],
        ),
    ]
