# Generated by Django 4.2.1 on 2023-06-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_profilepicture'),
        ('posts', '0003_alter_posts_postpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='participatedPost',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='participatingUsers',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='likers', to='users.users'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postPicture',
            field=models.ImageField(upload_to='posts/'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Participants',
        ),
    ]
