# Generated by Django 4.2.1 on 2023-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_profilepicture'),
        ('posts', '0004_remove_participants_participatedpost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='users.users'),
        ),
    ]
