# Generated by Django 4.2.1 on 2023-06-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
