# Generated by Django 4.2.1 on 2023-06-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to='media/profile_pics/'),
        ),
    ]
