# Generated by Django 4.2.1 on 2023-09-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dataAC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=6)),
                ("mark", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=20)),
                ("conectionCode", models.IntegerField(max_length=10)),
            ],
        ),
    ]
