# Generated by Django 4.2.1 on 2023-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataAC", "0002_alter_dataac_conectioncode"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataac",
            name="mode",
            field=models.CharField(
                choices=[("Auto", "Auto"), ("Manual", "Manual")],
                default="Auto",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dataac",
            name="status",
            field=models.CharField(
                choices=[("On", "On"), ("Off", "Off")], default="Off", max_length=10
            ),
        ),
    ]
